M48
; #@! TF.GenerationSoftware,LibrePCB,LibrePCB,2.1.1
; #@! TF.CreationDate,2026-10-04T17:57:12
; #@! TF.ProjectId,CO2-Sensor,06764a5f-d6f5-4d99-a3b7-4686052c3b4a,v1
; #@! TF.Part,Single
; #@! TF.SameCoordinates
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,MechanicalDrill
T1C0.65
; #@! TA.AperFunction,MechanicalDrill
T2C1.5
; #@! TA.AperFunction,MechanicalDrill
T3C3.2
%
G90
G05
M71
T1
X9.11Y6.905
X14.89Y6.905
T2
X14.25Y2.7
X9.75Y2.7
T3
X21.0Y8.0
X3.0Y67.0
X21.0Y67.0
X3.0Y8.0
T0
M30
